services:
  - type: web
    name: darkx-mini-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node start.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: BOT_NAME
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: PREFIX
        value: "."
      - key: MAX_SESSIONS
        value: "1"
